# This file contains the settings for your Django project.
# Django is a high-level Python web framework that encourages rapid development and clean, pragmatic design.
# A Django project is a collection of settings, configurations, and apps that make up a web application.

"""
Django settings for Littlelemon project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# The BASE_DIR setting defines the project's base directory.
# All other paths in the project will be relative to this directory.
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# The SECRET_KEY is a unique, secret key for this Django installation.
# It is used for cryptographic signing and should be kept secret.
# In a production environment, this should be loaded from an environment variable or a secrets management tool.
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(7rhfhl1%j6n1fo=7dzbo^lvyxbveo@zy#@4z(wn@=#h$@w_h_'

# The DEBUG setting enables or disables debug mode.
# When DEBUG is True, Django will show detailed error pages if an exception is raised.
# This is useful for development, but it should be set to False in a production environment for security reasons.
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# The ALLOWED_HOSTS setting is a list of strings representing the host/domain names that this Django site can serve.
# This is a security measure to prevent HTTP Host header attacks.
# In development, this can be an empty list. In production, you should add your domain name(s) here.
ALLOWED_HOSTS = []


# Application definition

# The INSTALLED_APPS setting is a list of all the Django apps that are installed in this project.
# An app is a web application that does something – e.g., a weblog system, a database of public records or a small poll app.
# Django comes with a few built-in apps, and you can add your own apps to this list.
INSTALLED_APPS = [
    # The admin app provides a ready-to-use interface for managing your site's content.
    'django.contrib.admin',
    # The auth app provides a user authentication system.
    'django.contrib.auth',
    # The contenttypes app is a framework for hooking into Django's content type system.
    'django.contrib.contenttypes',
    # The sessions app is a framework for handling user sessions.
    'django.contrib.sessions',
    # The messages app is a framework for displaying one-time notification messages to the user (also known as "flash messages").
    'django.contrib.messages',
    # The staticfiles app manages static files (CSS, JavaScript, images, etc.).
    'django.contrib.staticfiles',
    # The rest_framework app is a powerful and flexible toolkit for building Web APIs.
    'rest_framework',
    # This is your custom app for the Littlelemon API.
    'LittlelemonAPI',
    'django_filters',
    'rest_framework.authtoken'
]

# The MIDDLEWARE setting is a list of middleware to be executed during the request/response processing.
# Middleware is a framework of hooks into Django’s request/response processing. 
# It’s a light, low-level “plugin” system for globally altering Django’s input or output.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# The ROOT_URLCONF setting is the Python path to your project's root URLconf.
# A URLconf is a mapping between URL patterns (regular expressions) and view functions.
ROOT_URLCONF = 'Littlelemon.urls'

# The TEMPLATES setting is a list of settings for all template engines to be used in the project.
# Templates are used to generate HTML dynamically.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# The WSGI_APPLICATION setting is the Python path to a WSGI application object that the Django development server will use.
# WSGI (Web Server Gateway Interface) is a specification that describes how a web server communicates with web applications.
WSGI_APPLICATION = 'Littlelemon.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# The DATABASES setting is a dictionary of all the databases to be used in the project.
# By default, Django uses a SQLite database, which is a lightweight, file-based database.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# The AUTH_PASSWORD_VALIDATORS setting is a list of validators that are used to check the strength of users' passwords.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# The LANGUAGE_CODE setting is the default language code for this Django installation.
LANGUAGE_CODE = 'en-us'

# The TIME_ZONE setting is the default time zone for this Django installation.
TIME_ZONE = 'UTC'

# The USE_I18N setting enables or disables Django's translation system.
USE_I18N = True

# The USE_TZ setting enables or disables timezone-aware datetimes.
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# The STATIC_URL setting is the URL to use when referring to static files located in STATIC_ROOT.
STATIC_URL = 'static/'

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES':[
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
        'rest_framework_xml.renderers.XMLRenderer',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE':2,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
}