# This is a migration file.
# Migration files are generated by Django when you run the 'makemigrations' command.
# They contain a record of the changes that you have made to your models.
# Django uses these files to update the database schema when you run the 'migrate' command.

# Generated by Django 6.0 on 2025-12-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    # The 'initial' attribute indicates that this is the first migration for this app.
    initial = True

    # The 'dependencies' attribute is a list of the migrations that this migration depends on.
    # In this case, there are no dependencies because this is the first migration.
    dependencies = [
    ]

    # The 'operations' attribute is a list of the operations that should be performed when this migration is applied.
    operations = [
        # The CreateModel operation creates a new database table for the Book model.
        migrations.CreateModel(
            name='Book',
            fields=[
                # The 'id' field is an auto-incrementing primary key.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # The 'title' field is a character field with a maximum length of 255 characters.
                ('title', models.CharField(max_length=255)),
                # The 'author' field is a character field with a maximum length of 255 characters.
                ('author', models.CharField(max_length=255)),
                # The 'price' field is a decimal field with a maximum of 5 digits and 2 decimal places.
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                # The 'indexes' option is used to create database indexes on the table.
                # Indexes can improve the performance of database queries.
                'indexes': [models.Index(fields=['price'], name='Littlelemon_price_f5581b_idx')],
            },
        ),
    ]