# This is a migration file.
# It was generated by Django when the 'makemigrations' command was run.
# This migration creates the MenuItem model, removes the index on the Book model's price field, and deletes the Book model.

# Generated by Django 6.0 on 2025-12-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    # This migration depends on the previous migration, '0001_initial'.
    dependencies = [
        ('LittlelemonAPI', '0001_initial'),
    ]

    # The 'operations' attribute is a list of the operations that should be performed when this migration is applied.
    operations = [
        # The CreateModel operation creates a new database table for the MenuItem model.
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                # The 'id' field is an auto-incrementing primary key.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # The 'title' field is a character field with a maximum length of 255 characters.
                ('title', models.CharField(max_length=255)),
                # The 'price' field is a decimal field with a maximum of 6 digits and 2 decimal places.
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                # The 'inventory' field is a small integer field.
                ('inventory', models.SmallIntegerField()),
            ],
        ),
        # The RemoveIndex operation removes the index on the 'price' field of the 'Book' model.
        migrations.RemoveIndex(
            model_name='book',
            name='Littlelemon_price_f5581b_idx',
        ),
        # The DeleteModel operation deletes the 'Book' model and its corresponding database table.
        migrations.DeleteModel(
            name='Book',
        ),
    ]